### ISSUE TITLE
Fix limit switch of the torso

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/amigo_bringup#57]
https://github.com/tue-robotics/amigo_bringup/blob/62dc9f698bb50291a40639db33391861d95c176d/parameters/hardware/actuators/spindle_controller.ops#L85

**Comment by hvrooy** [comment]
Testing showed that the cable of the upper limit switch was broken close to the switch. Solution is to replace the limit switch with a new one. This has been done, and tested. Everything is OK now.

The software has to be adjusted to enable the switch again though...

**Comment by MatthijsBurgh** [comment]
@hvrooy switch replaced?

**Comment by MatthijsBurgh** [comment]
Fixed by #65
